name: appdiet
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.0+12

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter_sdk: ">=2.2.0"

dependencies:
  bloc: ^8.0.2
  cloud_firestore: ^3.1.5
  cloud_functions: ^3.0.3
  equatable: ^2.0.3
  expandable: ^5.0.1
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_remote_config: ^1.0.3
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  folding_cell: ^1.0.2
  font_awesome_flutter: ^9.1.0
  formz: ^0.4.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  meta: ^1.7.0
  multi_image_picker: ^4.8.01
  package_info_plus: ^1.3.0
  pedantic: ^1.11.1
  provider: ^6.0.1
  sign_button: ^2.0.1
  syncfusion_flutter_charts: ^19.2.62
  syncfusion_flutter_pdfviewer: ^19.3.55-beta
  table_calendar: ^3.0.2
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/
